### ISSUE TITLE
evil-escape package for alternative Esc keybindings

### ISSUE THREAD

**Issue by practicalli-johnny** [corgi-emacs/corgi#24]
Not everyone has a convenient location of the `Esc` key on their keyboard, requiring a rebinding of keys in the OS or a slower transition between insert and normal mode.

Consider adding the [evil-escape package](https://github.com/syl20bnr/evil-escape) to provide a simple mechanism to bind a two-character key binding as an alternative to pressing the `Esc` key.

```
(setq-default evil-escape-key-sequence "jk")
```

#### Reference
* https://github.com/syl20bnr/evil-escape

**Comment by plexus** [comment]
I don't see a need to add this to any of the existing corgi meta-packages, but I see little harm in adding it to the sample config, with a comment about what it is.

**Comment by davidh38** [comment]
I tried to put the following into the config, but i get the error "wrong argument". Is there some way of handling this in corgi?
```
 (insert
  ("jk" "Escap" evil-escape-key-sequence)
  )

```
