### ISSUE TITLE
Integrating 'jj' or 'jk' into corgi config.

### ISSUE THREAD

**Issue by davidh38** [corgi-emacs/corgi#29]
Is there in easy way to integrate 'jk' or 'jj' into the corgi configuration instead of 'ESC'?

**Comment by theophilusx** [comment]
Are you talking about being able to hit 'jk' or 'jj' quickly while in
insert mode and be switched into normal mode? If so, I think that is an
evil configuration, which means it would just be a matter of setting the
appropriate values in your init file. I would check the evil docs.

Note that one of the benefits of corgi is that it is a minimal
configuration which leaves the user with full control. Manyu aspects can
be tweaked in your init.el file and you can add additional packages with
minimal overhead. Unlike other 'canned' configurations, corgi encourages
you to modify your init.el file and add/change the set of installed
features/packages. With corgi, init.el is just your starting point, not
the end goal.
