### ISSUE TITLE
Typo User instead of corgi

### ISSUE THREAD

**Issue by umbrellaid** [corgi-emacs/corgi#34]
https://github.com/corgi-emacs/corgi/blob/52580808e7b257fc06340852cb780b3e4737b4c7/corgi_manual.org?plain=1#L592

Typo "user" to "corgi"
Current Text:
- ~SPC f e S~ - Open user-signals (all built-in signal mappings)
Corrected Text:
- ~SPC f e S~ - Open corgi-signals (all built-in signal mappings)

More context:
- ~SPC f e k~ - Open user-keys, create it if it doesn't exist
- ~SPC f e s~ - Open user-signals, create it if it doesn't exist
- ~SPC f e K~ - Open corgi-keys (all built-in bindings)
- ~SPC f e S~ - Open user-signals (all built-in signal mappings)

**Comment by plexus** [comment]
PR appreciated!

**Comment by umbrellaid** [comment]
I tried to submit a pull request. I don't know what I am doing, so let me know if you need something different.
