### ISSUE TITLE
Unable to boot cider off a fresh corgi install?

### ISSUE THREAD

**Issue by shellandbull** [corgi-emacs/corgi#36]
original clojure-emacs/cider#3715

## Expected behavior

Invoking `cider-jack-in-clj` to boot a `cider` server should boot the cider server off a fresh corgi install

## Actual behavior

The error `Symbol’s value as variable is void: cider-clojure-cli-parameters` happens. Here's what I see on screen on debug mode

<img width="727" alt="Screenshot 2024-06-13 at 8 43 45 AM" src="https://github.com/clojure-emacs/cider/assets/3522106/e614db59-714f-4cf9-b450-d41038bf8be4">

## Steps to reproduce the problem

- Install `emacs` via `homebrew`
- Install Corgi https://github.com/corgi-emacs/corgi
- Open any `.clj` file
- Run the command `cider-jack-in-clj`

## Environment & Version information

```
1,7 GHz Quad-Core Intel Core i7
```

### CIDER version information

`CIDER 1.5.0-snapshot (package: 1.5.0-snapshot)`

### Lein / Clojure CLI version

`Clojure CLI version 1.11.2.1446`

`Leiningen 2.11.2 on Java 21.0.2 OpenJDK 64-Bit Server VM`

💡 my project uses `deps.edn`

### Emacs version

```
GNU Emacs 29.3
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

### Operating system

Macbook Sonoma 14.5 

### JDK distribution

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by shellandbull** [comment]
This is the bit of the code that fails:

```
;; Most annoying JVM "feature" of all time
;; https://docs.cider.mx/cider/troubleshooting.html#empty-java-stacktraces
(defun corgi/around-cider-jack-in-global-options (command project-type)
  (if (eq 'clojure-cli project-type)
      (concat cider-clojure-cli-parameters
              " -J-XX:-OmitStackTraceInFastThrow")
    (funcall command project-type)))
```

**Comment by shellandbull** [comment]
I reinstalled the package and I can now boot a cider REPL

Syntax highlighting is gone and the error I get now is:

failed to define function `cider--setup-menu-for-clojure-major-mode`

**Comment by vemv** [comment]
It looks like cider and clojure-mode would need a bump.

**Comment by daslu** [comment]
(just commenting that I could reproduce the problem in a clean install in my environment   :pray: )

**Comment by shellandbull** [comment]
@daslu could you please show what version of corgi/cider/clojure-mode are you using in order to have it all working? 😄

**Comment by daslu** [comment]
Here are the contents of my `.emacs.d/straight/versions/default.el`:

```elisp
(("el-get" . "a5ba5852648a90ee0cde9fb5d72e69497d260eec")
 ("emacsmirror-mirror" . "93992ccb277a9b38537cae5ce25c0ce4fb80fdb1")
 ("gnu-elpa-mirror" . "ab9bcb0be30511d4fff7e413135507cebc447f7c")
 ("melpa" . "060c87774d09bc17dd059244c69feeb16646754f")
 ("nongnu-elpa" . "119e5d4ac0d253b6f58749212f48b497d36a558e")
 ("straight.el" . "b3760f5829dba37e855add7323304561eb57a3d4")
 ("use-package" . "a6e856418d2ebd053b34e0ab2fda328abeba731c"))
:gamma
```

.. and `.emacs.d/straight/versions/corgi.el`:

```elisp
;;; -*- no-byte-compile: t -*-
(("a.el" . "93e5ed8c495794d1ba3c04b43041b95ce01079b1")
 ("aggressive-indent-mode" . "cb416faf61c46977c06cf9d99525b04dc109a33c")
 ("annalist.el" . "134fa3f0fb91a636a1c005c483516d4b64905a6d")
 ("avy" . "ba5f035be33693d1a136a5cbeedb24327f551a92")
 ("cider" . "68974c9fb6ee6e95a4568c46a9c4371b24d2f0e9")
 ("clj-ns-name" . "2a0898ba7888a07724dc40cdbba282371b921fd0")
 ("clj-refactor.el" . "f368c56c83843396b160440f472a661a3b639862")
 ("clojure-mode" . "b6f41d74904daa9312648f3a7bea7a72fd8e140b")
 ("company-mode" . "1005540b1cdf176cbcf893b2fa83d2075cbbe3ca")
 ("corkey" . "1af271783e4df98d101ca14f49e4b6d62a544fa9")
 ("dash.el" . "7fd71338dce041b352f84e7939f6966f4d379459")
 ("diminish.el" . "6b7e837b0cf0129e9d7d6abae48093cf599bb9e8")
 ("dumb-jump" . "dbb915441a2b66f2fbb954ff5de2723c5a4771d4")
 ("elisp-slime-nav" . "8588d80d414aee1fafce5b9da0e913612ee0bcdd")
 ("emacs-undo-fu" . "f9c39c248cb965cd3c7cb3c8e15a4eee71921f8c")
 ("emacs-which-key" . "129f4ebfc74f207ac82978f6d90d8b4bb1a55cf9")
 ("emacs-winum" . "c5455e866e8a5f7eab6a7263e2057aff5f1118b9")
 ("evil" . "6fa371222f5d56cf96103aa301da8bcbf6c15cc2")
 ("evil-cleverparens" . "8c45879d49bfa6d4e414b6c1df700a4a51cbb869")
 ("evil-collection" . "a075a4e439ac7fe2cc57e5bba910291820fd31f1")
 ("evil-surround" . "2bc8aa6425f1311e985cf51ea6b5233c1ee6ce1c")
 ("expand-region.el" . "7e5bbe2763c12bae3e77fe0c49bcad05ff91dbfe")
 ("goto-chg" . "278cd3e6d5107693aa2bb33189ca503f22f227d0")
 ("goto-last-change.el" . "58b0928bc255b47aad318cd183a5dce8f62199cc")
 ("hydra" . "9e9e00cb240ea1903ffd36a54956b3902c379d29")
 ("jump.el" . "55caa66a7cc6e0b1a76143fd40eff38416928941")
 ("map" . "3d80a6d7cdc7d9e5760290fa95db4da992612837")
 ("multiple-cursors.el" . "aae47aebc0ae829211fa1e923232715d8e327b36")
 ("paredit" . "8330a41e8188fe18d3fa805bb9aa529f015318e8")
 ("parseclj" . "4d0e780e00f1828b00c43099e6eebc6582998f72")
 ("parseedn" . "e1de65e463adac2c8b46fc4b24d48ca62b74f23d")
 ("plexmacs" . "24e6a147dac872e1af9f540c2806f54eb25ffcc1")
 ("popup-el" . "3bf430270c74dad830ab9d776aab23cbf3ea3953")
 ("projectile" . "b014d79f5bca2103cf055b27334ad89f007a6ac8")
 ("queue" . "130c2d656cd5d7376552272fab9e50a7c37d0c4a")
 ("rainbow-delimiters" . "a32b39bdfe6c61c322c37226d66e1b6d4f107ed0")
 ("s.el" . "08661efb075d1c6b4fa812184c1e5e90c08795a9")
 ("sesman" . "e0f555f963c9f02f8e4a50e06fc353eb4c15ee77")
 ("smartparens" . "37f77bf2e2199be9fe27e981317b02cfd0e8c70e")
 ("smex" . "55aaebe3d793c2c990b39a302eb26c184281c42c")
 ("spinner" . "34905eae12a236753fa88abc831eff1e41e8576e")
 ("string-edit-at-point" . "87936d816ae24184dd83688136531b6b6f1943fe")
 ("swiper" . "7489968257a74f176c0d1de7ec8bd1e2011f0db4")
 ("treepy.el" . "3ac940e97f3d03e48ca9d7fcd74916a9b01c72f3")
 ("use-package" . "a7422fb8ab1baee19adb2717b5b47b9c3812a84c")
 ("walkclj" . "ce4e7713d801b03f94f5da9898fce09718380ed4")
 ("xclip" . "4772beb5579e13910c89c482a2e41271253c646b")
 ("yasnippet" . "5cbdbf0d2015540c59ed8ee0fcf4788effdf75b6"))
:beta
```

I guess one could try using these versions of the git commits of various packages, but possibly the problem is elsewhere.

Maybe it'd be better to continue this discussion after we hear some feedback from the `corgi` authors. Possibly they have an idea about where we should look.

**Comment by plexus** [comment]
Yeah I had already noticed this but hadn't had time to look into it properly. The preferred thing would be to do a general bump of all versions (straight pull all and copy the versions file), and then fix any issues due to upstream breaking changes so we're back at a stable point.

**Comment by daslu** [comment]
Nice. 

`straight-pull-all` did fix it for me (after a clean install). :pray:

**Comment by shellandbull** [comment]
Awesome work everyone! I think we can mark this as solved, my thanks 😄

**Comment by plexus** [comment]
If either of you could commit your versions file into corgi-packages that would be much appreciated!

**Comment by daslu** [comment]
Nice, is this the file that needs to be updated?
https://github.com/corgi-emacs/corgi-packages/blob/main/corgi-versions.el

**Comment by plexus** [comment]
Yes, please!

**Comment by shellandbull** [comment]
@daslu / @plexus I'll raise this 😄

**Comment by shellandbull** [comment]
🙈 it's my first time writing lisp

My local versions file is the same as the one on the repo. But my corgi emacs now works, could someone please help me raise this PR? It would be my first in the Clojure ecosystem so a bit of a personal landmark for me

**Comment by shellandbull** [comment]
Hello @plexus 😄 I managed to raise a PR https://github.com/corgi-emacs/corgi-packages/pull/18 sorry for the delays!
