### ISSUE TITLE
Sample missing corgi completion ui

### ISSUE THREAD

**Issue by Ramblurr** [corgi-emacs/corgi#38]
After https://github.com/corgi-emacs/corgi-packages/pull/10# the sample condit here is out of date. We need to include the new corgi completion ui package.

I'll try to PR it this week, just making this issue first so it doesn't get forgotten.

@oxalorg

**Comment by daslu** [comment]
Thanks for explaining the problem. Actually, for a couple of weeks, I had no idea how to use Corgin in a fresh install.

For now, the following workaround seems to work for me so I can keep using Corgi:

(1)
```bash
cd ~/.emacs.d/staight/repos/corgi-packages
git checkout 22b2eea74d94e65ab0d743a926f18af600629a65
```
(bringing it back before the troublesome changes)

(2)
remove all files under `~/.emacs.d/straight` except for `~/.emacs.d/staight/repos/corgi-packages`

(3)
restart emacs and let is reinstall all packages

**Comment by oxalorg** [comment]
@daslu @Ramblurr thanks for the update on this! Missed this notification somehow, fixing this now and making sure `sample-config` just works!

**Comment by daslu** [comment]
Oh, wonderful, thanks!

**Comment by oxalorg** [comment]
Changes here b67d85d and https://github.com/corgi-emacs/corgi-packages/commit/009e2560adb80dba096219adc32e330aa9367daa should fix fresh installs of corgi using the sample-config.

I've tried a fresh new install on my machine and it worked! If there are still any issues, do let me know 🙌 / reopen this issue!

Tried using: 
```bash
emacs --init-directory sample-config
```

**Comment by daslu** [comment]
Thank you so much!
